### PR TITLE
Upgrading

### PR DESCRIPTION
**Pull request by mlucool**
Hi,

I have created the following PR to update the versions of eslint allowed, upgrade babel, and adding '.js' as a type of file that can be processed. Please let me know if you want me to split this into two PR or make any changes.

### CODE REVIEW

**Comment by alexkuz** [comment]
Thank you! One PR is ok, the only thing is that there're two `eslint` dependencies now, the one in `peerDependencies` is enough I guess.

**Comment by mlucool** [comment]
In npm3 that is no longer the case.

http://blog.npmjs.org/post/110924823920/npm-weekly-5
"We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed."

**Comment by alexkuz** [comment]
Oh, right. Merging!

**Comment by alexkuz** [comment]
Now in version 0.1.0.

**Comment by mlucool** [comment]
:+1: thanks for the quick turn around time!

**Pull request merged**
